services:

  postgres-expense-manager:
    image: postgres:16
    container_name: postgres-expense-manager
    ports:
      - "5450:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: expense_manager
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  